simulation:
  duration_days: 7
  ticks_per_major: 360 # (e.g., if a major tick is 1 hour, and a minor tick is 10 seconds)
  random_seed: 42

market:
  grid_resolution: 1000 # Example value
  initial_riders: 1000
  initial_drivers: 200
  rider_population:
    price_sensitivity_dist: [0.5, 0.2] # [mean, std_dev]
    time_sensitivity_dist: [0.5, 0.2]
    preference_score_dist: [0.0, 0.3]
    rides_per_week_dist: [3.0, 1.5]
    pct_with_app_a_only: 0.20
    pct_with_app_b_only: 0.20
    pct_with_both_apps: 0.60
  driver_population:
    price_sensitivity_dist: [0.7, 0.1]
    eta_sensitivity_dist: [0.3, 0.1]
    preference_score_dist: [0.0, 0.2]
    pct_exclusive: 0.15

platforms:
  A:
    matcher:
      max_order_tries: 3
  B:
    matcher:
      max_order_tries: 3
